#!/bin/bash
function list_policy_docs(){
    local policy_arn=$1
    echo $policy_arn | sed 's/^/  /';
    version_id=$(aws iam get-policy --policy-arn $policy_arn --query 'Policy.DefaultVersionId' --output text)
    aws iam get-policy-version --policy-arn $policy_arn --version-id $version_id --query 'PolicyVersion.Document' --output json | jq -cr '.Statement[]' | sed 's/^/   /';
}
function list_inline_policy_docs(){
    local role_name=$1
    local policy_name=$2
    echo inline:${policy_name} | sed 's/^/  /';
    aws iam get-role-policy --role-name $role_name --policy-name $policy_name --query 'PolicyDocument' --output json | jq -rc '.Statement[]' | sed 's/^/   /';
}
function list_role_policies_docs(){
    local role_arn=$1
    local role_name="${role_arn##*/}"
    aws iam get-role --role-name $role_name --query 'Role.AssumeRolePolicyDocument' --output json | jq -rc '.Statement[]' | sed 's/^/   /';
    aws iam list-attached-role-policies --role-name "${role_name}" --query 'AttachedPolicies[*].PolicyArn' --output text | tr '\t' '\n' | while read policy_arn; do
        list_policy_docs $policy_arn
    done
    aws iam list-role-policies --role-name $role_name --query 'PolicyNames[*]' --output text | tr '\t' '\n' | while read policy_name; do
        list_inline_policy_docs $role_name $policy_name
    done
}
